spring:
  redis:
    port: 6379
    host: localhost
    password:
    timeout: 6000ms
    jedis:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
        #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        #连接池中最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 5
  cache:
    type: redis
cache:
  test:
    expire-time: 180
    name: test
  default:
    expire-time: 200
